name: ChannelTap
main: feildmaster.modules.chanchat.chantap.Governor
version: 1.0
author: feildmaster
depend: [ChannelChat]

commands:
  tap:
    description: Main function for tapping channels. :D

permissions:
  Chan.Tap:
    description: Allows players to tap channels/players